version: '3'

services:

        nodejs-server:

                build:

                        context: ./

                ports:

                        - "3070:3099"

                container_name: node-api

                volumes:

                        - ./api:/usr/src/app/api

                        - /usr/src/app/api/node_modules

        react-ui:

                build:

                        context: ./

                ports:

                        - "3010:3098"

                container_name: react-ui

                stdin_open: true

                volumes:

                        - ./my-app:/usr/src/app/my-app
                        - /usr/src/app/my-app/node_modules